### PR TITLE
Update Plot Legend/Label Functionality

### PR DESCRIPTION
**Pull request by YigitElma**
This PR solves the issue mentioned in #629 .

If you use,
```python
from desc.plotting import plot_1d, plot_surfaces, plot_fsa
from desc.examples import get

eq = get("HELIOTRON")
plot_fsa(eq,"|B|",label="Magnetic Field Magnitude");
plot_surfaces(eq,label="Magnetic Field Magnitude");
plot_1d(eq,"|B|",label="Magnetic Field Magnitude");
```

It now gives,
image
image
image

without additional plt.legend() command

### CODE REVIEW

**Comment by YigitElma** [comment]
I don't know why my commits for other PR shows up here. First 4commits are for PR #744 .

**Comment by f0uriest** [comment]
Can you check what happens if multiple things are plotted to the same axis? eg
```python
fig, ax = plt.subplots()
for i, eq in enumerate(eqf):
    plot_1d(eq, "iota", ax=ax, label=f"eq{i}")
```
I think it might try to draw the legend multiple times

**Comment by dpanici** [comment]
> Can you check what happens if multiple things are plotted to the same axis? eg
> 
> ```python
> fig, ax = plt.subplots()
> for i, eq in enumerate(eqf):
>     plot_1d(eq, "iota", ax=ax, label=f"eq{i}")
> ```
> 
> I think it might try to draw the legend multiple times

FWIW this happens with `plot_qs_error` as well, the `legend=False` flag is what I find I have to pass to that function when I want to plot multiple equilibria on the same figure, then I just call `ax.legend()` after all the calls to `plot_qs_error`

**Comment by YigitElma** [comment]
`python
from desc.plotting import plot_1d, plot_surfaces, plot_fsa
from desc.examples import get

eq = get("HELIOTRON")
fig, ax = plt.subplots(nrows=1, ncols=2)

for i in range(2):
    plot_1d(eq, "|B|", ax=ax[i], label=f"Bmag{i}");
    
fig, ax = plt.subplots()
for i in range(2):
    plot_1d(eq, "iota", ax=ax, label=f"eq{i}")
    plot_1d(eq, "|B|", ax=ax, label=f"Bmag{i}")
`
image
image

If you mean creating a subplot? to create subplot you need to specify row and columns as this one. For just multiple lines on same frame, no need for additional things

**Review by dpanici — DISMISSED** [review]

**Review by ddudt — COMMENTED** [review]
Why are the installation instructions changed in this PR? You should remove those changes.

**Comment by YigitElma** [comment]
> Why are the installation instructions changed in this PR? You should remove those changes.

I accidentally created this branch from PR #744 branch. How can I delete those commits?

**Review by dpanici — APPROVED** [review]

**Review by f0uriest — APPROVED** [review]

**Pull request merged**
