### PR TITLE
Devtools - Linting Update

### PR DESCRIPTION
**Pull request by MothVine**
Added scripts and configs for linting with Flake8 and Pylint to a new Devtools folder.  These check not only for formatting but also for unused code,  duplicated code, and can be set to check for standardized naming of variables, functions, methods, etc.  The config is currently very verbose, with only a few possible error flags being ignored.

### CODE REVIEW

**Comment by f0uriest** [comment]
Are the ``*rc`` files needed, or can  that config stuff be put into ``setup.cfg``, ``pyproject.toml`` etc?

**Comment by f0uriest** [comment]
Are the ``*rc`` files needed, or can  that config stuff be put into ``setup.cfg``, ``pyproject.toml`` etc?

**Comment by MothVine** [comment]
I think the pylint needs to be standalone; flake8 does not and can be merged in.  I'll be working a bunch tmrw and will test out pylint's contraints

**Comment by f0uriest** [comment]
@MothVine is this ready to go now?

**Comment by MothVine** [comment]
This is ready to be reviewed and merged once tests pass now!

**Comment by MothVine** [comment]
Codecov might show an error in the comparison because I hadn't set my fork of DESC up on it yet; running codecov over there as well.  If @f0uriest or @ddudt want to review it, before merge?  

Will stick to branching the PlasmaControl/DESC hereon out rather than working my own fork; it also caused confusion when I fixed black on my local fork but couldn't replicate the problem on master, cause I didn't realize Rory had patched it there the same day.  Talking about PR protocol today was helpful.  

Will be working from MAE building tomorrow and most of this week I think, especially as I'm certain nobody in my house caught my covid and spread it back to me.  So should be able to discuss outputs of linting files and what we want removed or kept more easily.

**Review by dpanici — APPROVED** [review]
this looks good, should we maybe spend an afternoon trying to reduce the amount of warnings before we merge? Or maybe we can do the merge and once we have the tools we can do that another time

**Pull request merged**
