### PR TITLE
Rerun regcoil notebook with corrected plotly options

### PR DESCRIPTION
**Pull request by dpanici**

### CODE REVIEW

**Comment by f0uriest** [comment]
I don't see the new plots on RTD built from this PR, is it just me?

**Comment by dpanici** [comment]
@f0uriest it works now I think, I guess saving the notebook from inside VScode can make the figure not save correctly? I saved the notebook from jupyter lab instead and it shows up fine in docs

**Review by YigitElma — APPROVED** [review]

**Comment by YigitElma** [comment]
https://desc-docs.readthedocs.io/en/latest/notebooks/tutorials/coil_optimization_REGCOIL.html#REGCOIL-Algorithm-with-QuadraticFlux-and-SurfaceCurrentRegularization-Objective-Functions I approve it but why do we get the RuntimeWarning here?

**Comment by dpanici** [comment]
> https://desc-docs.readthedocs.io/en/latest/notebooks/tutorials/coil_optimization_REGCOIL.html#REGCOIL-Algorithm-with-QuadraticFlux-and-SurfaceCurrentRegularization-Objective-Functions I approve it but why do we get the RuntimeWarning here?

I set the trust region radius to infinite, and I think that causes it

**Pull request merged**
