### PR TITLE
Add paper info

### PR DESCRIPTION
**Pull request by f0uriest**
Adds pdfs of published and to-be published works, and input files and scripts to generate plots for conlin2022

@ddudt @dpanici can you add any necessary input files/scripts and instructions to the folders for your papers
@ddudt do you still have the scripts for generating the plots from the 2020 paper? we can add that as well with instructions on how to checkout and run the matlab version

### CODE REVIEW

**Comment by f0uriest** [comment]
I feel like we should just merge this for now and update later

**Comment by dpanici** [comment]
small comment on Rory's stuff, in your plotting notebook you have `heliotron_scan.h5` as the heliotron output file to load from, but if someone runs the files again the output file will by default be named `heliotron_scan_output.h5`
same for the `W7X_4step`

**Comment by f0uriest** [comment]
Thanks, just fixed those.

**Comment by dpanici** [comment]
@ddudt how much memory does the optimize take? I cannot run it locally on my laptop

**Pull request merged**
