### PR TITLE
Support `numpy 2.0`

### PR DESCRIPTION
**Pull request by YigitElma**

### CODE REVIEW

**Comment by YigitElma** [comment]
My bad, to test `numpy` @f0uriest needs to make sure that `orthax` and `interpax` works fine with it. I guess `interpax` supports it but it is not released yet.

**Comment by f0uriest** [comment]
> My bad, to test `numpy` @f0uriest needs to make sure that `orthax` and `interpax` works fine with it. I guess `interpax` supports it but it is not released yet.

I'll try to do that tomorrow or Friday

**Comment by YigitElma** [comment]
> > My bad, to test `numpy` @f0uriest needs to make sure that `orthax` and `interpax` works fine with it. I guess `interpax` supports it but it is not released yet.
> 
> I'll try to do that tomorrow or Friday

No worries, I just wanted to test if it works or not.

**Comment by YigitElma** [comment]
Temporarily changing the tests to use whatever matplotlib is installed in the first place. Downgrading to 3.7.2 causes tests to immediately fail.

**Comment by YigitElma** [comment]
Apparently, we get some `ValueError: numpy masked arrays are not supported as direct inputs to JAX functions. Use arr.filled() to convert the value to a standard numpy array.`. Someone can use this branch later to solve the problem. Until then, I am closing this PR since I won't work on it.

**Comment by YigitElma** [comment]
This might change our `matplotlib` dependency! Check that too!

**Comment by dpanici** [comment]
regenerate plot figs with latest matplotlib version, then this should be good to go

**Comment by YigitElma** [comment]
- I regenerated all baseline images (tho there is no visual difference). There was 1 extra baseline image that doesn't have a test anymore (test_qh_optimization3), I deleted that.
- Upgraded CI workflows to use matplotlib 3.9.2

**Review by dpanici — APPROVED** [review]

**Pull request merged**
