### PR TITLE
Fix `_print_value_fmt` for some objectives and fix some latex labels

### PR DESCRIPTION
**Pull request by YigitElma**
#1189 changed the format of `_print_value_fmt` some recent merged PR's added new objectives that shouldn't work with the new format and throw `IndexError: Replacement index 2 out of range for positional args tuple`.

Also, I think I missed one of the objectives during that PR. This fixes the formats.

And some small label fixes.

### CODE REVIEW

**Comment by unalmis** [comment]
Can you also fix `<|B|>_axis` and `B_phi|r,t` latex labels in this pr?

**Review by unalmis — DISMISSED** [review]

**Comment by rahulgaur104** [comment]
Are these all the objectives  in the current master where  the formatting specification is used after _print_value_fmt?

**Comment by YigitElma** [comment]
> Are these all the objectives in the current master where the formatting specification is used after _print_value_fmt?

I searched `_print_value_fmt =` on VS Code and checked the strings. These should be all of them, unless a PR gets merged without checking the print.

**Comment by YigitElma** [comment]
> Can you also fix `<|B|>_axis` and `B_phi|r,t` latex labels in this pr?

What is this exactly? You can add your commit here if it is a quick fix

**Review by rahulgaur104 — APPROVED** [review]

**Review by unalmis — APPROVED** [review]

**Review by rahulgaur104 — APPROVED** [review]

**Review by f0uriest — APPROVED** [review]

**Review by dpanici — APPROVED** [review]

**Review by ddudt — APPROVED** [review]

**Pull request merged**
