### PR TITLE
Stop modding of non-periodic angles

### LINKED ISSUE #1173: Mod SFL theta by 2pi inside of `vmec.VMECIO.compute_theta_coords`
_Originally posted by @dpanici in https://github.com/PlasmaControl/DESC/pull/1153#discussion_r1712110839_

### LINKED ISSUE #1180: don't mod angles; they are not periodic
Recall  single valued functions $f$ that are periodic in $(\theta, \zeta)$ obey $f(\theta, \zeta) = f(\theta + j  2 \pi, \zeta + k 2 \pi)$. Of course $\zeta \neq \zeta + k 2 \pi$.

1. I think we should not mod any of the angles we compute $\theta, \zeta, \phi, \alpha, \vartheta$ inside our compute functions. Otherwise, we can run into issues because there are functions of interest which are not periodic. [^1]

We don't mod $\phi$ right now, but if we did, attempts to map coordinates $\alpha \in \mathbf{R}, \phi \subset \mathbf{R}$ using $\alpha = \vartheta  \text{mod} (2 \pi) - \iota (\phi \text{mod} (2 \pi))$ will give incorrect results because the map $\alpha \colon \vartheta, \phi \mapsto \alpha(\vartheta, \phi)$ is not periodic. Likewise since the "branch cut" (for my lack of better description) we choose to define $\alpha$ on is centered at $\phi =\vartheta = 0$, we want that

$$\lim_{\vert\phi\vert \to \infty} \vert \frac{\partial \alpha}{\partial \rho}\vert (\rho, \vartheta, \phi)  = \infty \text{ when } \frac{\partial \iota}{\partial \rho} \neq 0$$

but this will not be satisfied if we mod $\phi$ in the compute function.

Currently on `master` we mod $\vartheta$ and $\alpha$. ~This doesn't cause issues for my work,~ but FYI it would impede computing $\phi$ through the relation $(\vartheta - \alpha) / \iota = \phi$.

2. Inside the coordinate mapping routines, we mod the coordinates by the period common to all periodic functions of those coordinates. This is fine if we only care about feeding the output to periodic functions, and should help accelerate convergence of the root finding. If we care about feeding these coordinates to non periodic functions, such as a radial derivative of $\alpha$,  dependency, or chain multiple coordinate mappings together, then we could get wrong results.

I think 1. can be done without drawbacks. ~Not sure if 2 affects anyone.~ 2 affects me

[^1]: For example, if we edit the compute function of $\phi = \phi mod $2\pi$, then [this test](https://github.com/PlasmaControl/DESC/blob/e178e4c2355cabf3e406c4403ce4404a5616c2bc/tests/test_equilibrium.py#L72)  will fail. Note that the output of `_map_clebsch_coordinates` remains correct because it never computes $\phi$, while the general `map_coordinates` is affected.

### PR DESCRIPTION
**Pull request by unalmis**
Resolves #1180 and resolves #1173 .

Here is what $\theta$ looks like now on #1119 :
theta

Likewise, all the other quantities have become smooth bumps, as desired.

### CODE REVIEW

**Review by f0uriest — APPROVED** [review]

**Comment by rahulgaur104** [comment]
>Here is what θ looks like now on https://github.com/PlasmaControl/DESC/pull/1119 

Does it work for negative zeta values? What if I give zeta in [-4pi, 4pi] to map_coordinates. Will the theta still be smooth?

**Comment by unalmis** [comment]
> > Here is what θ looks like now on #1119
> 
> Does it work for negative zeta values? What if I give zeta in [-4pi, 4pi] to map_coordinates. Will the theta still be smooth?

Where we start $\zeta$ seems to not matter. However there is still an issue, I believe completely separate to this PR. I have found that $\theta$ is still discontinuous every two toroidal transits, which is causing issues: https://github.com/PlasmaControl/DESC/pull/1119#discussion_r1766062255. 

Here is a plot of $\theta(\alpha=0, \zeta)$. 

tt

**Review by rahulgaur104 — APPROVED** [review]
Approving, but I am slightly concerned that it might break the ballooning PR. 
Merge at will.

**Comment by unalmis** [comment]
For the equilibrium I computed this plot on, two toroidal transits corresponds to one poloidal transit. So it seems the information of which poloidal transit $\theta$ is at is lost somewhere

**Comment by unalmis** [comment]
So the issue is probably that I'm paramterizing my FourierChebyshev series for $\theta$ using $\alpha \in [-\pi, \pi]$ and I should be using $\alpha \in [0, 2 \pi]$. I'll look into this on the weekend.

**Comment by unalmis** [comment]
I resolved the remaining discontinuous issue fyi.

**Pull request merged**
