### PR TITLE
Optimization updates from Quasi-Symmetry branch

### PR DESCRIPTION
**Pull request by ddudt**
Highlights:

- 2nd-order optimal perturbation capability added
- Quasi-symmetry objective functions have been validated against STELLOPT benchmarks
- Bug fixes and fields added to the VMEC-like NetCDF output generated by `VMECIO.save()`
- Bug fixes in `booz_xform` implementation
- Other miscellaneous fixes and improvements

### CODE REVIEW

**Comment by f0uriest** [comment]
Looks like there's a few issues with tests and differences with the current master. 
The main ones I noticed were with the new profile API.
Do we want the compute_volume/area/aspect ratio/radius methods to also be pure functions? that way they could be differentiated and used in optimization.
Also is there any way we can increase the test coverage? Looks like this will reduce it overall by ~4%

**Comment by f0uriest** [comment]
Also, do we need to double the quadrature weights for non-symmetric grids? For volume and area I think they might be only counting half the domain

**Comment by ddudt** [comment]
- My latest commits should fix the Profile API references and resolve the failed tests. 
- The compute_volume/area/radius/etc. methods will eventually be turned into pure functions to use in optimization. They will have to go in the `compute_funs.py` file and get called by Configuration in the same style as `compute_magnetic_field()`, etc. But I will wait to make that change in the upcoming rewrite of the Objective Functions structure. 
- The main reason coverage is decreasing is because I added a lot more derived quantities (like `bsubumnc`, etc.) to the NetCDF output file from `VMECIO.save()`. I will try to add tests for those with comparisons to the VMEC solution before merging. 
- Do we want the symmetric grid to still have the weight of the full volume (not only the symmetric half)? I guess we probably do. If so, we just need to double the weights in the method `Grid._enforce_symmetry()`. The default Quadrature Grid used for `compute_volume()` and `compute_cross_section_area()` covers the full domain so it is not an issue for those methods.

**Review by f0uriest — COMMENTED** [review]
I marked a few things that need to get cleaned up and ideally tested before merging into master

**Review by f0uriest — APPROVED** [review]
Looks good now

**Pull request merged**
